# Generated by Django 5.2.6 on 2025-09-24 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit_approval', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='id',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='emis_paid_on_time',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='id',
        ),
        migrations.AddField(
            model_name='customer',
            name='current_debt',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='customer',
            name='customer_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='loan',
            name='date_approved',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='loan_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customer',
            name='approved_limit',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customer',
            name='monthly_salary',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone_number',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='loan',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='loan',
            name='interest_rate',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='loan',
            name='loan_amount',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='loan',
            name='monthly_installment',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='loan',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
