# Generated by Django 5.2.6 on 2025-09-25 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit_approval', '0002_remove_customer_id_remove_loan_emis_paid_on_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='emis_paid_on_time',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='loan',
            name='loan_status',
            field=models.CharField(default='Pending', max_length=20),
        ),
        migrations.AddField(
            model_name='loan',
            name='num_of_repayments',
            field=models.IntegerField(default=0),
        ),
    ]
